apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secret-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/amar-chand/test
    path: argocd/bitnami-secret/
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: kubeseal
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true