apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/
commonLabels:
  purpose: Argocd-demo
  env: prod
nameSuffix: -prod
replicas:
  - name: web-frontend
    count: 3
  - name: customers
    count: 4

